on:
  push:
  schedule:
    - cron: '0 22 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: python env
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install bs4

      - name: 'Get Info'
        run: python ./py.py
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USER_NMAE }}
          password: ${{ secrets.MAIL_PWD }}
          subject: 今日新闻简报推送 (${{env.REPORT_DATE}})
          body: file://result.txt
          to: 864562082@qq.com
          from: GitHub Actions
          content_type: text/html
